version: "3.3"

services:

   web:
     image: nginx
     ports:
         - 10080:80
         - 12345:12345
         - 12346:12346
# ip add add 192.168.56.41 dev enp0s8
# vi /etc/ssh/sshd_config
#ListenAddress 192.168.56.31
# service sshd restart
         - 192.168.56.41:22:22
     volumes:
       - ./conf.d:/etc/nginx/conf.d
       - ./nginx.conf:/etc/nginx/nginx.conf
     environment:
       - NGINX_HOST=nginx1
       - NGINX_PORT=80



